# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: darkholme 0.9.0 ruby lib

Gem::Specification.new do |s|
  s.name = "darkholme"
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Massive Danger"]
  s.date = "2014-02-22"
  s.description = "An entity-component system in Ruby for libgdx"
  s.email = "evan@massivedanger.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "darkholme.gemspec",
    "lib/darkholme.rb",
    "lib/darkholme/bitset.rb",
    "lib/darkholme/component.rb",
    "lib/darkholme/engine.rb",
    "lib/darkholme/entity.rb",
    "lib/darkholme/family.rb",
    "lib/darkholme/system.rb",
    "spec/lib/darkholme/bitset_spec.rb",
    "spec/lib/darkholme/component_spec.rb",
    "spec/lib/darkholme/engine_spec.rb",
    "spec/lib/darkholme/entity_spec.rb",
    "spec/lib/darkholme/family_spec.rb",
    "spec/lib/darkholme/system_spec.rb",
    "spec/lib/darkholme_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/mock_classes.rb"
  ]
  s.homepage = "http://github.com/evanwalsh/darkholme"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "An entity-component system in Ruby for libgdx"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<pry>, ["~> 0.9.12.6"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0.0.beta1"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 4.2.6"])
      s.add_development_dependency(%q<inch>, ["~> 0.2.3"])
    else
      s.add_dependency(%q<pry>, ["~> 0.9.12.6"])
      s.add_dependency(%q<rspec>, ["~> 3.0.0.beta1"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, ["~> 4.2.6"])
      s.add_dependency(%q<inch>, ["~> 0.2.3"])
    end
  else
    s.add_dependency(%q<pry>, ["~> 0.9.12.6"])
    s.add_dependency(%q<rspec>, ["~> 3.0.0.beta1"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, ["~> 4.2.6"])
    s.add_dependency(%q<inch>, ["~> 0.2.3"])
  end
end

